### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by rorrewang** [Jingtao-Li-CVer/HyperFree#28]
Hi @Jingtao-Li-CVer , I tried to build conda environment and run Seg_Any_HSI.py on my own rgb image(2495, 3182, 3), but got error as:
```
(hyper) wly@wly:/mnt/PC/HyperFree$ python tes.py                                                                                                                             
image (2495, 3182, 3)                                                                                                                                                                                 
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [36,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [37,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [38,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [40,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [41,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [42,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [44,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [45,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [46,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.                   
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [48,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [49,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [50,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [53,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [54,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [56,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4133,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [4128,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/mnt/PC/HyperFree/tes.py", line 113, in <module>
    masks = mask_generator.generate(img, wavelengths, GSD=GSD)
  File "/home/wly/anaconda3/envs/hyper/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/PC/HyperFree/HyperFree/automatic_mask_generator.py", line 157, in generate
    mask_data = self._generate_masks(image, spectral_lengths, GSD)
  File "/mnt/PC/HyperFree/HyperFree/automatic_mask_generator.py", line 227, in _generate_masks
    crop_data = self._process_crop(image, crop_box, layer_idx, orig_size, spectral_lengths, GSD)
  File "/mnt/PC/HyperFree/HyperFree/automatic_mask_generator.py", line 259, in _process_crop
    self.predictor.set_image(cropped_im, True, spectral_lengths, GSD)
  File "/mnt/PC/HyperFree/HyperFree/predictor.py", line 50, in set_image
    self.set_torch_image(input_image, image.shape[-2:], test_mode, spectral_lengths,GSD=GSD)
  File "/mnt/PC/HyperFree/HyperFree/predictor.py", line 82, in set_torch_image
    self.multi_scale_features= self.model.image_encoder(input_image, test_mode, spectral_lengths, GSD)
  File "/home/wly/anaconda3/envs/hyper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/PC/HyperFree/HyperFree/modeling/image_encoder.py", line 243, in forward
    weight=self.point_spectral_weight_bank_w[:,indices[1],:,:],
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Can you help me find out what mistakes I made?

My conda list:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
blosc                     1.21.5               hc2324a3_1    conda-forge
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.5               hb9d3cd8_0    conda-forge
ca-certificates           2025.7.14            hbd8a1cb_0    conda-forge
cairo                     1.16.0            ha00ac49_1009    conda-forge
certifi                   2025.7.14                pypi_0    pypi
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
charset-normalizer        3.4.2                    pypi_0    pypi
curl                      7.86.0               h2283fc2_1    conda-forge
cycler                    0.12.1                   pypi_0    pypi
expat                     2.7.1                hecca717_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.59.0                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
gdal                      3.4.1            py39h85832e7_6    conda-forge
geos                      3.10.2               h9c3ff4c_0    conda-forge
geotiff                   1.7.0                h509b78c_7    conda-forge
gettext                   0.25.1               h5888daf_0    conda-forge
gettext-tools             0.25.1               h5888daf_0    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.10                     pypi_0    pypi
joblib                    1.5.1                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
kealib                    1.4.15               hfe1a663_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7                    pypi_0    pypi
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.40                 h12ee557_0    defaults
lerc                      4.0.0                h0aef613_1    conda-forge
libarchive                3.5.2                hada088e_3    conda-forge
libasprintf               0.25.1               h8e693c7_0    conda-forge
libasprintf-devel         0.25.1               h8e693c7_0    conda-forge
libblas                   3.9.0           32_h59b9bed_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_3    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_3    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_3    conda-forge
libcblas                  3.9.0           32_he106b2a_openblas    conda-forge
libcurl                   7.86.0               h2283fc2_1    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.7.1                hecca717_0    conda-forge
libffi                    3.4.6                h2dba641_1    conda-forge
libgcc                    15.1.0               h767d61c_3    conda-forge
libgcc-ng                 15.1.0               h69a702a_3    conda-forge
libgdal                   3.4.1                hda961b2_6    conda-forge
libgettextpo              0.25.1               h5888daf_0    conda-forge
libgettextpo-devel        0.25.1               h5888daf_0    conda-forge
libgfortran               15.1.0               h69a702a_3    conda-forge
libgfortran-ng            15.1.0               h69a702a_3    conda-forge
libgfortran5              15.1.0               hcea5267_3    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   15.1.0               h767d61c_3    conda-forge
libhwy                    1.2.0                hf40a0c7_0    conda-forge
libiconv                  1.18                 h4ce23a2_1    conda-forge
libjpeg-turbo             2.1.4                h166bdaf_0    conda-forge
libjxl                    0.11.1               h7b0646d_2    conda-forge
libkml                    1.3.0             h01aab08_1016    conda-forge
liblapack                 3.9.0           32_h7ac8fdf_openblas    conda-forge
liblzma                   5.8.1                hb9d3cd8_2    conda-forge
liblzma-devel             5.8.1                hb9d3cd8_2    conda-forge
libnetcdf                 4.8.1           nompi_h329d8a1_102    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hb9d3cd8_1    conda-forge
libopenblas               0.3.30          pthreads_h94d23a6_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     14.5                 he2d8382_0    conda-forge
librttopo                 1.1.0                hf69c175_9    conda-forge
libspatialite             5.0.1               ha867d66_15    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 15.1.0               h8f9b012_3    conda-forge
libstdcxx-ng              15.1.0               h4852527_3    conda-forge
libtiff                   4.4.0                h82bc61c_5    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.6.0                hd42ef1d_0    conda-forge
libxcb                    1.17.0               h9b100fa_0    defaults
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.9.14               haae042b_4    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
matplotlib                3.5.1                    pypi_0    pypi
minizip                   4.0.3                h0ab5242_0    conda-forge
muparser                  2.3.5                h5888daf_0    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
nspr                      4.36                 h5888daf_0    conda-forge
nss                       3.100                hca3bf56_0    conda-forge
numpy                     1.22.4                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
opencv-contrib-python     4.11.0.86                pypi_0    pypi
opencv-python             4.8.0.76                 pypi_0    pypi
opencv-python-headless    4.5.5.64                 pypi_0    pypi
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   3.1.8                h7b32b05_0    conda-forge
packaging                 25.0                     pypi_0    pypi
pandas                    2.3.1                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
pillow                    11.3.0                   pypi_0    pypi
pip                       25.1               pyhc872135_2    defaults
pixman                    0.46.2               h29eaf8c_0    conda-forge
poppler                   22.01.0              h1434ded_2    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                14.5                 ha7cec9f_0    conda-forge
proj                      9.0.0                h93bde94_1    conda-forge
pthread-stubs             0.3                  h0ce48e5_1    defaults
pycocotools               2.0.7                    pypi_0    pypi
pyparsing                 3.2.3                    pypi_0    pypi
python                    3.9.18          h0755675_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.9                      8_cp39    conda-forge
pytz                      2025.2                   pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
requests                  2.32.4                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                78.1.1           py39h06a4308_0    defaults
six                       1.17.0                   pypi_0    pypi
snappy                    1.2.1                h8bd8927_1    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
threadpoolctl             3.6.0                    pypi_0    pypi
tiledb                    2.7.2                h3f4058f_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torch                     1.13.0                   pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
typing-extensions         4.14.1                   pypi_0    pypi
tzcode                    2025b                hb9d3cd8_0    conda-forge
tzdata                    2025.2                   pypi_0    pypi
uriparser                 0.9.8                hac33072_0    conda-forge
urllib3                   2.5.0                    pypi_0    pypi
wheel                     0.45.1           py39h06a4308_0    defaults
xerces-c                  3.2.3                h8ce2273_4    conda-forge
xorg-libice               1.1.2                hb9d3cd8_0    conda-forge
xorg-libsm                1.2.6                he73a12e_0    conda-forge
xorg-libx11               1.8.12               h9b100fa_1    defaults
xorg-libxau               1.0.12               h9b100fa_0    defaults
xorg-libxdmcp             1.1.5                h9b100fa_0    defaults
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.12               hb9d3cd8_0    conda-forge
xorg-xorgproto            2024.1               h5eee18b_1    defaults
xz                        5.8.1                hbcc6ac9_2    conda-forge
xz-gpl-tools              5.8.1                hbcc6ac9_2    conda-forge
xz-tools                  5.8.1                hb9d3cd8_2    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```
Is it a problem caused by mismatch of packages?Or I can not use rgb images to inference?

**Comment by Jingtao-Li-CVer** [comment]
I have tried to use RGB images, and it works fine. 

You can email me and add WeChat if you need further help.

**Comment by rorrewang** [comment]
Thank you for your reply :) . But I tried again and got the same error. I guess it's because the number of channels in the tif image is not consistent with the RGB image? Can you please tell me how to correctly run RGB images? What other code should I modify besides changing the image path?

**Comment by Jingtao-Li-CVer** [comment]
Please change the input wavelengths as well.
